### PR TITLE
Added button for BookWyrm

### PR DESCRIPTION
**Pull request by MagicLike**
fixes https://github.com/JulianPrieber/littlelink-custom/discussions/322

### CODE REVIEW

**Review by JulianPrieber — CHANGES_REQUESTED** [review]
Please add new entries at the end of database/seeders/ButtonSeeder.php or else current buttons will break.

chrome_kP4yPT0Nao

**Comment by MagicLike** [comment]
> Please add new entries at the end of database/seeders/ButtonSeeder.php or else current buttons will break.
> 
> chrome_kP4yPT0Nao

before or after `text` and `icon`?

**Comment by JulianPrieber** [comment]
After: https://github.com/JulianPrieber/littlelink-custom/blob/91e33a8dcd629bbb926437c1cd43542fe7ead9d5/database/seeders/ButtonSeeder.php#L400

**Comment by MagicLike** [comment]
Done!

**Pull request merged**
