### PR TITLE
Add Trello css/logo --- Improve Youtube css/logo

### PR DESCRIPTION
**Pull request by Doncellup**

### CODE REVIEW

**Comment by JulianPrieber** [comment]
Looking good 👍 

> https://update.littlelink-custom.com/misc/trello_yt.html

**Comment by JulianPrieber** [comment]
Gonna merge this in a sec

**Comment by JulianPrieber** [comment]
Just for the record, if a new button is added, it has to be added to the database as well to show up on the Admin Panel.

This new entry has to be added to the file: [`/database/seeders/ButtonSeeder.php`](https://github.com/JulianPrieber/littlelink-custom/blob/main/database/seeders/ButtonSeeder.php).
The updater will then add all these entries to the database on update.

I added the entry for the Trello button with this commit -> https://github.com/JulianPrieber/littlelink-custom/commit/7dff61cc848a2883f4a6486112993f53d81ae1ea

**Comment by Doncellup** [comment]
Ah and little question: how can I update llc so that my improvements are effective for me?

**Comment by JulianPrieber** [comment]
Clone the repository to your local machine and run the following commands:

```
composer update -vvv

php artisan migrate
php artisan db:seed 
php artisan db:seed --class="AdminSeeder"
php artisan db:seed --class="PageSeeder"
php artisan db:seed --class="ButtonSeeder"
```

**Pull request merged**
